hyperfleet:
  api-url: "http://localhost:8000"
  api-version: "v1"
  token: ""
  gcp-project: "hcm-hyperfleet"
  namespace: "hyperfleet"

kubernetes:
  context: ""

maestro:
  consumer: "cluster1"
  http-endpoint: "http://localhost:8100"
  grpc-endpoint: "localhost:8090"
  namespace: "maestro"

port-forward:
  api-port: "8000"
  pg-port: "5432"
  maestro-http-port: "8100"
  maestro-http-remote-port: "8000"
  maestro-grpc-port: "8090"
  maestro-grpc-remote-port: "8090"

database:
  host: "localhost"
  port: "5432"
  name: "hyperfleet"
  user: "hyperfleet"
  password: "foobar-bizz-buzz"

rabbitmq:
  host: "localhost"
  mgmt-port: "15672"
  user: "guest"
  password: "guest"
  vhost: "/"

registry:
  name: ""
